### ISSUE TITLE
Getting time out when fetching information for DHL url tracking

### ISSUE THREAD

**Issue by thierrybucco** [awkward/Ocarina#18]
https://www.dhl.com/en/express/tracking.html?AWB=XXXXXXXXXX&brand=DHL

**Comment by thierrybucco** [comment]
Fixed it.
It was because of our custom user-agent. 
I added a public user-agent property on OcarinaManager.

ocarina.userAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"

**Comment by renssies** [comment]
The setting of the user agent is an awesome addition. 

When this library was created we wanted to be friendly to server admins and identify ourselves as a bot, that's why we changed the user agent. 

But I can still think of use cases where you want to keep the original user agent or set your own, so this is great :)

**Comment by renssies** [comment]
I've reviewed the PR and left some feedback, once you've implemented the feedback I will check it again and merge it of everything looks ok :)
